spring.application.name=batch
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#
spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always
#
spring.threads.virtual.enabled=true