spring.application.name=beans-to-boot

spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.threads.virtual.enabled=true